tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"

brew "editorconfig"
brew "git"
brew "git-lfs"
brew "neovim"
brew "packer"
brew "python"
brew "python@2"
brew "reattach-to-user-namespace"
brew "tmux"
brew "tree"
brew "zsh"

cask "docker-edge"
cask "font-input"
cask "kaleidoscope"
cask "kitty"
cask "sequel-pro-nightly"
cask "vagrant"
cask "vagrant-manager"
cask "vimr"
cask "virtualbox"
cask "virtualbox-extension-pack"
