#!/usr/bin/env ruby

require 'fileutils'
require 'open3'
require 'tmpdir'
require 'net/http'
require 'uri'

sourcedir = File.join(Dir.pwd, 'src')
tempdir = Dir.mktmpdir
home = File.expand_path('~')

puts "Installing dotfiles from '#{sourcedir}'"

puts "Copying files to '#{tempdir}'"
(Dir.entries(sourcedir).reject{ |f| f.start_with? '.' }).each do |f|
  FileUtils.cp_r(File.join(sourcedir, f), File.join(tempdir, ".#{f}"))
end

puts "Syncing files to '#{home}'"
Open3.popen3(
  'rsync',
  '-ar',
  '-Iah',
  '--safe-links',
  '--executability',
  "#{tempdir}/",
  home) do |stdin, stdout, stderr|
    stdout.read.split("\n").each do |line|
      puts "rsync: #{line}"
    end
  end

# Install Homebrew
brew_installer = File.join(tempdir, 'brew_install')

File.open(brew_installer, 'w', 0744) do |file|
  brew_uri = URI.parse("https://raw.githubusercontent.com/Homebrew/install/master/install")

  brew_response = Net::HTTP.get_response(brew_uri)

  file.write(brew_response.body)
end

system(brew_installer)

# Install Homebrew packages
system('brew bundle install')

FileUtils.rm_r(tempdir)
