#!/usr/bin/env ruby

require 'fileutils'
require 'open3'
require 'tmpdir'
require 'net/http'
require 'uri'

tempdir = Dir.mktmpdir
home = File.expand_path('~')

puts "Installing Homebrew"
brew_installer = File.join(tempdir, 'brew_install')

File.open(brew_installer, 'w', 0744) do |file|
  brew_uri = URI.parse("https://raw.githubusercontent.com/Homebrew/install/master/install")

  brew_response = Net::HTTP.get_response(brew_uri)

  file.write(brew_response.body)
end

system(brew_installer)

puts "Installing Homebrew Packages"
system('brew bundle install')

puts "Installing composer"
system(File.join(Dir.pwd, 'install_composer'))

puts "Installing composer packages"
system('composer global install')

puts "Installing pip packages"
system('pip3 install -r pip3.txt')

system('pip install -r pip2.txt')

puts "Cleaning Up"
FileUtils.rm_r(tempdir)
