#!/usr/bin/env sh

echo "Downloading composer-setup.php"

EXPECTED_SIGNATURE="$(wget -q -O - https://composer.github.io/installer.sig)"
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
ACTUAL_SIGNATURE="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"

if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]
then
    >&2 echo 'ERROR: Invalid installer signature'
    rm composer-setup.php
    exit 1
fi

echo "Installing composer to /usr/local/bin/composer"
php composer-setup.php --install-dir=/usr/local/bin --filename=composer --quiet
RESULT=$?

echo "Removing composer-setup.php"
rm composer-setup.php
exit $RESULT
