# load custom executable functions
for function in $ZSH_CONFIG/functions/*; do
  source $function
done

source $ZSH_CONFIG/functions/load_settings

[[ ! -f "${ZSH_LOCAL}/plugins.zsh" ]] && \
    antibody bundle < "${ZSH_CONFIG}/plugins.txt" > "${ZSH_LOCAL}/plugins.zsh"

source "${ZSH_LOCAL}/plugins.zsh"

zmodload zsh/termcap
zmodload zsh/terminfo

if (alias run-help > /dev/null); then
  unalias run-help
fi
autoload run-help
autoload -Uz vcs_info
autoload zmv

load_settings "${ZSH_CONFIG}/configs"

autoload -Uz compinit promptinit
promptinit
compinit -u

# completion; use cache if updated within 24h
#autoload -Uz compinit
#if [[ -n $HOME/.zcompdump(#qN.mh+24) ]]; then
#  compinit -d $HOME/.zcompdump;
#else
#  compinit -C;
#fi;
