setopt no_global_rcs

# load custom executable functions
for function in $ZSH_CONFIG/functions/*; do
  autoload -Uz +X $function
done

[[ ! -f "${ZSH_LOCAL}/plugins.zsh" ]] && \
    antibody bundle < "${ZSH_CONFIG}/plugins.txt" > "${ZSH_LOCAL}/plugins.zsh"

source "${ZSH_LOCAL}/plugins.zsh"

zmodload zsh/termcap
zmodload zsh/terminfo

if (alias run-help > /dev/null); then
  unalias run-help
fi
autoload run-help
autoload -Uz vcs_info
autoload zmv

load_settings "${ZSH_CONFIG}/configs"

autoload -Uz promptinit
promptinit
